### ISSUE TITLE
I want to ask some questions about MBC_GLMMs

### ISSUE THREAD

**Issue by DGYang77** [vavrajan/MBC_GLMMs#1]
Hello. I am a graduate student doing research on longitudinal data.

Currently, I am planning a study related to the mixture of GLMM, so I have a lot of interest in this package.

While following the tutorial, I have a question.
In the case of the example data, it seems that all cases of numeric, count, binary, ordinal, and nominal variables are included.

The package didn't work for data that excluded one or more of them. 
Is there any way to solve it?

**Comment by vavrajan** [comment]
I think it should work even when some types do not appear in the model. I certainly remember using it that way and successfully. Maybe we can arrange an on-line meeting to solve it?

**Comment by DGYang77** [comment]
I've seen several of your academic papers, and it seems you've done it successfully.
 
I tried deleting the "Ords" and "Cats" options from the function 'Metropolis_within_Gibbs_MBC_NumPoiBinOrdCat' to exclude ordinal and nominal variables.
But it didn't work as the options appeared asking for default values.

**Comment by vavrajan** [comment]
Deleting would not help, you have to use empty sets. Like:
Ords = c()
Cats = c()

**Comment by DGYang77** [comment]
Thanks. It does work. 
Your package seems to be really helpful.

**Comment by vavrajan** [comment]
That is good to hear! If any other problem occurs do no hesitate to contact me!

**Comment by DGYang77** [comment]
I've encountered an issue related to your packages.

When selecting the number of mixture, I used the log-likelihood of mixture of GLMMs. 
Generally, log-likelihoods tend to be negative, but in certain cases when using this package, they appear as very large positive values.
I think there are some problems in your packages and i want to know some insights from you.

Thank you for reading the messages.

**Comment by vavrajan** [comment]
I can have a look at it, however, it would be helpful to have some example where you encounter these problems.

**Comment by DGYang77** [comment]
<img width="165" alt="capture1" src="https://github.com/vavrajan/MBC_GLMMs/assets/114632082/5e1bad61-bd66-47cc-9010-2f713145829a">

When two model is fitted to univariate continuous longitudinal data, mcmcNum1 is assumed to have 1 cluster and mcmcNum is assumed to have 2 clusters. The log-likelihoods of each model are, -4918 and 1992.

**Comment by vavrajan** [comment]
I think that the current version of column "loglik" deserves a better description. 

Evaluation of the log-likelihood during sampling would be expensive. Hence, only a very crude version of it is computed. In particular, it is a by-product of updating the clustering probabilities, see file 'gibbs_pUig.c' for details. 
Full-conditional probabilities for unit _i_ require the following:

1. For each cluster g compute:
- log p(Y_i | X_i, b, U_i = g)       (sum over all observations and outcomes)
- log p(b_i | U_i = g)
- log p(U_i = g)
- sum all of the above
2. Scale the values to probabilities.
3. Sample a new cluster allocation U_i.
4. Add the value from step 1. (corresponding to the newly sampled cluster) to the 'loglik' parameter.

Then, 'loglik' contains the sum over all units. 

In case of G = 1, loglik consists of only log p(Y_i | X_i, b) + log p(b_i | U_i = g), which are both log-pdfs of normal distribution. 
I would have to make larger investigation on why is the 'loglik' positive under G=2. 

However, it hardly can be considered a classical log-likelihood. Therefore, I would avoid using it as a (model or G)-selection tool. Notice that the column 'loglik' is just auxiliary and is not used anywhere. I guess that I only used it as a detector of divergence/explosion while implementing and forgot to delete/redefine it. I will keep that in mind when creating an R package.

And one more thing, as mcmc approach this 'loglik' is just some parametric function of model parameters and hence the whole posterior distribution is approximated by the sampled values. 

I hope that my reply was helpful in understanding of what 'loglik' is. Thank you for noticing these little irregularities!
